title: Systems and Signals 414
description: A first introductory course in digital signal processing for undergraduate students
show_downloads: false
# theme: jekyll-theme-slate
theme: minima
github:
  is_project_page: false

# # Theme options
# minima:
#   social_links:
#     - title: Jekyll repository at GitHub
#       icon: github
#       url: "https://github.com/kamperh/ss414"

github_username: kamperh
youtube_username: "@kamperh"
linkedin_username: kamperh
