title: SS414
description: Introduction to digital signal processing
show_downloads: false
# theme: jekyll-theme-slate
theme: minima
github:
  is_project_page: false

# Theme options
minima:
  nav_pages:
    - readme.md#license
  social_links: []
  show_excerpts: false
